name: taptune
description: "一个基于大模型工作流实现的智能设置助手 TapTuneSDK，可以根据用户的需求从配置的所有设置项中快速选择正确的设置。"
version: 0.0.1
homepage: https://github.com/pamaforce/TapTuneSDK
repository: https://github.com/pamaforce/TapTuneSDK
issue_tracker: https://github.com/pamaforce/TapTuneSDK/issues
documentation: https://github.com/pamaforce/TapTuneSDK/wiki

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

